"use client";

import { FormEvent, useEffect, useState } from "react";
const API = process.env.NEXT_PUBLIC_API_URL || "http://localhost:8000";
type Criterion = { id:number; name:string; target:string; unlocks:string; status:string; track:string; isActive:boolean; nextTarget?:string|null };
type Summary = { id:number; shortTitle:string; progress:number };
type Program = { programName:string; durationWeeks:number; hevyRoutineIds:Record<string,string>; sessions:{name:string; focus:string; exercises:{name:string; sets:number; reps:string}[]}[] };
type Goal = { id:number; title:string; shortTitle:string; goalReadiness?:{percentage:number;criteria:Criterion[]}; competencies:{id:number;name:string;progress:number;verifiedExercise:string;currentValue:number;targetValue:number;unit:string;source?:string}[]; milestones:{id:number;title:string;target:string;completed:boolean;status:string}[]; workoutProgram?:Program; coachFeedback:{coachInsights:string[];adjustments?:string[];nextSteps?:string[]}[] };

export default function Home() {
  const [goal,setGoal] = useState<Goal>(); const [goals,setGoals] = useState<Summary[]>([]); const [busy,setBusy] = useState(false); const [error,setError] = useState(""); const [showNew,setShowNew] = useState(false);
  async function pick(id:number) { const response=await fetch(`${API}/goal/${id}`); if(response.ok) setGoal(await response.json()); }
  async function list() { const ids=JSON.parse(localStorage.getItem("goalforge.goalIds")||"[]") as number[]; const saved=await Promise.all(ids.map(async id=>{const response=await fetch(`${API}/goal/${id}`);return response.ok ? await response.json() as Goal : null})); setGoals(saved.filter(Boolean).map(item=>({id:item!.id,shortTitle:item!.shortTitle,progress:item!.goalReadiness?.percentage||0}))); }
  useEffect(()=>{const id=localStorage.getItem("goalforge.activeGoalId");if(id) void pick(Number(id));else void list()},[]);
  useEffect(()=>{if(goal){localStorage.setItem("goalforge.activeGoalId",String(goal.id));void list()}},[goal]);
  async function post(path:string,body?:unknown) { setBusy(true);setError("");try { const response=await fetch(API+path,{method:"POST",headers:body?{"Content-Type":"application/json"}:undefined,body:body?JSON.stringify(body):undefined});const payload=await response.json();if(!response.ok) throw new Error(payload.detail||"Request failed");setGoal(payload.goal||payload); } catch(reason) { setError(reason instanceof Error?reason.message:"Request failed"); } finally { setBusy(false); } }
  async function createGoal(event:FormEvent<HTMLFormElement>) { event.preventDefault(); const form=new FormData(event.currentTarget); const title=String(form.get("title")||"").trim(); if(!title) return; setBusy(true);setError("");try { const createdResponse=await fetch(`${API}/goal`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({title,description:String(form.get("description")||""),target_date:String(form.get("targetDate")||"")||null,current_abilities:{notes:String(form.get("abilities")||"")},user_profile:{}})}); const created=await createdResponse.json();if(!createdResponse.ok) throw new Error(created.detail||"Could not create goal"); const analyzedResponse=await fetch(`${API}/goal/analyze`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({goal_id:created.id})}); const analyzed=await analyzedResponse.json();if(!analyzedResponse.ok) throw new Error(analyzed.detail||"Could not analyze goal"); const ids=JSON.parse(localStorage.getItem("goalforge.goalIds")||"[]") as number[];localStorage.setItem("goalforge.goalIds",JSON.stringify([...new Set([...ids,analyzed.id])]));setGoal(analyzed);setShowNew(false); } catch(reason) { setError(reason instanceof Error?reason.message:"Could not create goal"); } finally { setBusy(false); } }
  const newGoalForm=<section className="card full"><div className="row"><div><h2 className="font-bold text-lg">Create another goal</h2><p className="intro">Your current goal remains saved in My Goals.</p></div>{goal&&<button type="button" onClick={()=>setShowNew(false)}>Cancel</button>}</div><form className="stack mt-3" onSubmit={createGoal}><label>Goal title<input name="title" required placeholder="e.g. Run a half marathon"/></label><label>What does success look like?<textarea name="description" placeholder="Describe the outcome and any important context."/></label><div className="formgrid"><label>Target date<input name="targetDate" type="date"/></label><label style={{gridColumn:"span 2"}}>Current abilities / constraints<input name="abilities" placeholder="e.g. Beginner runner, three sessions weekly"/></label></div><button disabled={busy} type="submit">{busy?"Creating…":"Create and analyze goal"}</button></form></section>;
  if(!goal) return <main className="shell"><Nav/>{error&&<p className="error">{error}</p>}{newGoalForm}</main>;
  const readiness=goal.goalReadiness; const tracks=Object.entries((readiness?.criteria||[]).reduce<Record<string,Criterion[]>>((all,item)=>{(all[item.track]||=[]).push(item);return all;},{}));
  return <main className="shell"><Nav/><div className="dashboard-layout"><aside className="card goal-sidebar"><div className="label">My goals</div><button type="button" disabled={busy} onClick={()=>setShowNew(true)}>+ New goal</button>{goals.map(item=><button className={`goal-switcher ${item.id===goal.id?"active":""}`} key={item.id} onClick={()=>pick(item.id)}><b>{item.shortTitle}</b><div className="progress"><i style={{width:`${item.progress}%`}}/></div><small>{item.progress}% goal readiness</small></button>)}</aside><div><div className="row mb-6"><h1 className="text-3xl font-black">{goal.title}</h1><button disabled={busy} onClick={()=>post(`/goal/${goal.id}/sync/hevy`)}>Sync Hevy</button></div>{error&&<p className="error">{error}</p>}<div className="grid">{showNew&&newGoalForm}
    <section className="card full"><div className="row"><div><div className="label">Goal readiness</div><div className="stat">{readiness?.percentage||0}%</div></div><span className="pill">GOAL READINESS AGENT</span></div><div className="progress"><i style={{width:`${readiness?.percentage||0}%`}}/></div>{tracks.map(([track,steps])=>{const active=steps.find(item=>item.isActive);const display=active||steps.at(-1)!;const complete=!active;const activeIndex=active?steps.indexOf(active):steps.length;const undoItem=activeIndex>0?steps[activeIndex-1]:undefined;return <div className="item mt-3" key={track}><div className="row"><div><div className="label">{track} · Step {steps.indexOf(display)+1} of {steps.length}</div><b>{complete?"✓ ":"○ "}{display.name}: {display.target}</b></div><div className="row">{undoItem&&<button disabled={busy} onClick={()=>post(`/goal/${goal.id}/readiness/${undoItem.id}/manual`,{completed:false})}>Undo</button>}{!complete&&<button disabled={busy} onClick={()=>post(`/goal/${goal.id}/readiness/${display.id}/manual`,{completed:true})}>Check off</button>}</div></div><small>Unlocks: {display.unlocks}</small>{!complete&&display.nextTarget&&<div className="intro mt-1">Next goal: {display.name} — {display.nextTarget}</div>}{complete&&<div className="intro mt-1">Track complete.</div>}</div>})}</section>
    <section className="card full"><div className="row"><div><h2 className="font-bold text-lg">Current Plan</h2><p className="intro">Review your plan before sending it to Hevy.</p></div>{goal.workoutProgram&&<button disabled={busy} onClick={()=>post(`/goal/${goal.id}/program/export/hevy`)}>{Object.keys(goal.workoutProgram.hevyRoutineIds||{}).length?"Update Hevy routines":"Export plan to Hevy"}</button>}</div>{goal.workoutProgram?<><div className="plan-summary mt-3"><div><div className="label">Current workout block</div><b>{goal.workoutProgram.programName}</b></div><span>{goal.workoutProgram.durationWeeks} weeks</span></div><div className="grid mt-3">{goal.workoutProgram.sessions.map(session=><div className="plan-session" style={{gridColumn:"span 4"}} key={session.name}><b>{session.name}</b><p className="plan-focus">{session.focus}</p><div className="plan-exercises">{session.exercises.map(exercise=><div key={exercise.name}><span>{exercise.name}</span><span>{exercise.sets} × {exercise.reps}</span></div>)}</div></div>)}</div></>:<p>Generate a plan from the goal analysis.</p>}</section>
    <section className="card wide"><h2 className="font-bold text-lg">AI Coach Feed</h2>{goal.coachFeedback.length ? <div className="stack mt-3">{goal.coachFeedback.at(-1)?.coachInsights.map((insight,index)=><p className="intro" key={index}>{insight}</p>)}{goal.coachFeedback.at(-1)?.adjustments?.map(item=><div className="item" key={item}><b>Adjustment:</b> {item}</div>)}{goal.coachFeedback.at(-1)?.nextSteps?.map(item=><div className="item" key={item}><b>Next step:</b> {item}</div>)}</div> : <p>Sync Hevy to receive coaching.</p>}</section><section className="card side"><h2 className="font-bold text-lg">Milestones</h2>{goal.milestones.map(milestone=><div className="item milestone-item mt-3" key={milestone.id}><div className="milestone-heading"><StatusIcon completed={milestone.completed}/><div><b>{milestone.title}</b><small>{milestone.target}</small></div></div></div>)}</section>
    <section className="card full"><h2 className="font-bold text-lg">Competency Map</h2><div className="grid mt-3">{goal.competencies.map(competency=><div className="item" style={{gridColumn:"span 4"}} key={competency.id}><div className="row"><b>{competency.name}</b><b>{competency.progress}%</b></div><div className="progress"><i style={{width:`${competency.progress}%`}}/></div><div className="label">Verified through Hevy</div><b>{competency.verifiedExercise}</b><p className="intro">{competency.currentValue} / {competency.targetValue} {competency.unit}{competency.source?" · synced from Hevy":" · awaiting Hevy evidence"}</p></div>)}</div></section>
    </div><div className="mt-8 text-center"><a className="pill" href="/activity">View agent activity →</a></div></div></div></main>;
}
function Nav(){return <nav className="nav"><div className="brand">Goal<span>Forge</span> AI</div></nav>;}
function StatusIcon({completed}:{completed:boolean}){return completed?<svg className="milestone-icon complete" viewBox="0 0 24 24" role="img" aria-label="Completed"><circle cx="12" cy="12" r="10"/><path d="m7.5 12.2 3 3.1 6-6.5"/></svg>:<svg className="milestone-icon loading" viewBox="0 0 24 24" role="img" aria-label="In progress"><circle cx="12" cy="12" r="8.5"/><path d="M12 3.5a8.5 8.5 0 0 1 8.5 8.5"/></svg>;}
